version: '2.1'

services:

  log-restart:
    logging:
      driver: "journald"
    restart: unless-stopped

  log-dns-restart:
    extends: log-restart
    dns:
      - 172.20.0.21

  msp-log-dns-restart:
    extends: log-dns-restart
    networks:
      - msp